# This is the production variant of
# docker deployment for adeq-backend
version: '3'
services:

  # development instance
  webapp:
    image: index.docker.io/adeq2019/webapp:master
    container_name: 'webapp'
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
      - URL=http://ec2-54-162-54-159.compute-1.amazonaws.com/development/api/

  # nginx for port forwarding and proxy server
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - webapp
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs

  watchtower:
    image: v2tec/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: --interval 10 --cleanup
